version: '3.7'

services:
  proxy:
    image: nginx:stable-alpine
    container_name: nginx-proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  db:
    image: 'postgres'
    container_name: db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - validation-db:/var/lib/postgresql/data

  backend:
    image: 'validation-backend'
    container_name: backend
    build:
      context: validation-backend
      dockerfile: dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db

  frontend:
    image: 'validation-frontend'
    container_name: frontend
    build:
      context: validation-frontend
      dockerfile: dockerfile
    volumes:
      - react:/app
      - node_modules:/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend

volumes:
  validation-db:
  react:
  node_modules: